# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: Cache@2
  inputs:
    key: yarn | $(Agent.OS) | yarn.lock
    path: $(YARN_CACHE_FOLDER)
    restoreKeys: |
      yarn | $(Agent.OS)
      yarn
  displayName: 'Cache Yarn packages'

- task: NodeTool@0
  inputs:
    checkLatest: true
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    # yarn install --frozen-lockfile
    yarn install
  displayName: 'Run yarn install'

- script: |
    yarn run build
  displayName: 'Run yarn build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
    CleanTargetFolder: true
  displayName: 'Copy build directory to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'
